DROP TABLE IF EXISTS dishes, orders CASCADE;

CREATE TABLE dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  dish_name VARCHAR(255) NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  image TEXT
);

CREATE TABLE orders(
  id SERIAL PRIMARY KEY NOT,
  users_id INTEGER NOT NULL REFERENCE users(id) ON DELETE CASCADE,
  dish_id INTEGER NOT NULL REFERENCE dishes(id) ON DELETE CASCADE,
  duration INTEGER DEFAULT 0
);
